/**
 * Built-in merchant knowledge base: maps a lowercase substring found in a
 * transaction's merchant/name to a spending category. Canada-focused, with the
 * common global brands. Matching is longest-pattern-first (so "uber eats" beats
 * "uber"). Unknown merchants return null so the transaction is left blank.
 */
const MERCHANT_PATTERNS: [pattern: string, category: string][] = [
  // --- Groceries ---
  ["loblaws", "Groceries"],
  ["no frills", "Groceries"],
  ["nofrills", "Groceries"],
  ["real canadian superstore", "Groceries"],
  ["superstore", "Groceries"],
  ["zehrs", "Groceries"],
  ["fortinos", "Groceries"],
  ["valu-mart", "Groceries"],
  ["independent grocer", "Groceries"],
  ["provigo", "Groceries"],
  ["maxi", "Groceries"],
  ["metro", "Groceries"],
  ["food basics", "Groceries"],
  ["sobeys", "Groceries"],
  ["safeway", "Groceries"],
  ["freshco", "Groceries"],
  ["foodland", "Groceries"],
  ["longo", "Groceries"],
  ["farm boy", "Groceries"],
  ["t&t supermarket", "Groceries"],
  ["save-on-foods", "Groceries"],
  ["save on foods", "Groceries"],
  ["whole foods", "Groceries"],
  ["bulk barn", "Groceries"],
  ["costco", "Groceries"],
  ["iga", "Groceries"],
  ["m&m food", "Groceries"],
  ["grocery", "Groceries"],
  ["supermarket", "Groceries"],

  // --- Dining Out ---
  ["uber eats", "Dining Out"],
  ["ubereats", "Dining Out"],
  ["doordash", "Dining Out"],
  ["skip the dishes", "Dining Out"],
  ["skipthedishes", "Dining Out"],
  ["tim hortons", "Dining Out"],
  ["tim horton", "Dining Out"],
  ["starbucks", "Dining Out"],
  ["second cup", "Dining Out"],
  ["mcdonald", "Dining Out"],
  ["a&w", "Dining Out"],
  ["wendy", "Dining Out"],
  ["burger king", "Dining Out"],
  ["subway", "Dining Out"],
  ["harvey", "Dining Out"],
  ["swiss chalet", "Dining Out"],
  ["boston pizza", "Dining Out"],
  ["pizza pizza", "Dining Out"],
  ["little caesars", "Dining Out"],
  ["domino", "Dining Out"],
  ["pizza", "Dining Out"],
  ["kfc", "Dining Out"],
  ["popeyes", "Dining Out"],
  ["chipotle", "Dining Out"],
  ["taco bell", "Dining Out"],
  ["dairy queen", "Dining Out"],
  ["five guys", "Dining Out"],
  ["the keg", "Dining Out"],
  ["montana", "Dining Out"],
  ["kelsey", "Dining Out"],
  ["milestones", "Dining Out"],
  ["earls", "Dining Out"],
  ["cactus club", "Dining Out"],
  ["jollibee", "Dining Out"],
  ["nando", "Dining Out"],
  ["freshii", "Dining Out"],
  ["booster juice", "Dining Out"],
  ["chatime", "Dining Out"],
  ["bubble tea", "Dining Out"],
  ["restaurant", "Dining Out"],
  ["cafe", "Dining Out"],
  ["coffee", "Dining Out"],
  ["sushi", "Dining Out"],
  ["ramen", "Dining Out"],
  ["shawarma", "Dining Out"],
  ["donair", "Dining Out"],
  ["grill", "Dining Out"],
  ["bistro", "Dining Out"],

  // --- Transport (gas, transit, rideshare, parking) ---
  ["canadian tire gas", "Transport"],
  ["costco gas", "Transport"],
  ["petro-canada", "Transport"],
  ["petro canada", "Transport"],
  ["petrocan", "Transport"],
  ["esso", "Transport"],
  ["shell", "Transport"],
  ["chevron", "Transport"],
  ["husky", "Transport"],
  ["ultramar", "Transport"],
  ["pioneer energy", "Transport"],
  ["mobil", "Transport"],
  ["gas station", "Transport"],
  ["uber", "Transport"],
  ["lyft", "Transport"],
  ["presto", "Transport"],
  ["ttc", "Transport"],
  ["go transit", "Transport"],
  ["green p", "Transport"],
  ["impark", "Transport"],
  ["parking", "Transport"],
  ["zipcar", "Transport"],
  ["communauto", "Transport"],
  ["enterprise rent", "Transport"],
  ["hertz", "Transport"],
  ["turo", "Transport"],

  // --- Travel ---
  ["air canada", "Travel"],
  ["westjet", "Travel"],
  ["porter airlines", "Travel"],
  ["flair air", "Travel"],
  ["air transat", "Travel"],
  ["via rail", "Travel"],
  ["expedia", "Travel"],
  ["booking.com", "Travel"],
  ["airbnb", "Travel"],
  ["hotels.com", "Travel"],
  ["marriott", "Travel"],
  ["hilton", "Travel"],
  ["fairmont", "Travel"],
  ["best western", "Travel"],
  ["airline", "Travel"],
  ["hotel", "Travel"],

  // --- Subscriptions ---
  ["netflix", "Subscriptions"],
  ["spotify", "Subscriptions"],
  ["disney+", "Subscriptions"],
  ["disney plus", "Subscriptions"],
  ["crave", "Subscriptions"],
  ["amazon prime", "Subscriptions"],
  ["prime video", "Subscriptions"],
  ["apple.com/bill", "Subscriptions"],
  ["apple music", "Subscriptions"],
  ["icloud", "Subscriptions"],
  ["youtube premium", "Subscriptions"],
  ["google one", "Subscriptions"],
  ["dropbox", "Subscriptions"],
  ["adobe", "Subscriptions"],
  ["microsoft 365", "Subscriptions"],
  ["office 365", "Subscriptions"],
  ["notion", "Subscriptions"],
  ["openai", "Subscriptions"],
  ["chatgpt", "Subscriptions"],
  ["audible", "Subscriptions"],
  ["patreon", "Subscriptions"],
  ["hbo", "Subscriptions"],
  ["paramount+", "Subscriptions"],
  ["dazn", "Subscriptions"],

  // --- Entertainment ---
  ["cineplex", "Entertainment"],
  ["landmark cinema", "Entertainment"],
  ["cinema", "Entertainment"],
  ["imax", "Entertainment"],
  ["theatre", "Entertainment"],
  ["ticketmaster", "Entertainment"],
  ["stubhub", "Entertainment"],
  ["live nation", "Entertainment"],
  ["steam games", "Entertainment"],
  ["steampowered", "Entertainment"],
  ["playstation", "Entertainment"],
  ["xbox", "Entertainment"],
  ["nintendo", "Entertainment"],
  ["eb games", "Entertainment"],
  ["gamestop", "Entertainment"],

  // --- Health & pharmacy ---
  ["shoppers drug mart", "Health"],
  ["shoppers drug", "Health"],
  ["rexall", "Health"],
  ["pharmasave", "Health"],
  ["jean coutu", "Health"],
  ["pharmacy", "Health"],
  ["dental", "Health"],
  ["dentist", "Health"],
  ["physio", "Health"],
  ["optometr", "Health"],
  ["clinic", "Health"],
  ["hospital", "Health"],

  // --- Personal Care ---
  ["sephora", "Personal Care"],
  ["mac cosmetics", "Personal Care"],
  ["sally beauty", "Personal Care"],
  ["salon", "Personal Care"],
  ["barber", "Personal Care"],
  ["spa", "Personal Care"],

  // --- Fitness ---
  ["goodlife", "Fitness"],
  ["good life fitness", "Fitness"],
  ["la fitness", "Fitness"],
  ["anytime fitness", "Fitness"],
  ["planet fitness", "Fitness"],
  ["fit4less", "Fitness"],
  ["orangetheory", "Fitness"],
  ["crossfit", "Fitness"],
  ["peloton", "Fitness"],
  ["yoga", "Fitness"],
  ["gym", "Fitness"],

  // --- Housing & Utilities (telecom + utilities) ---
  ["rogers", "Housing & Utilities"],
  ["bell canada", "Housing & Utilities"],
  ["bell mobility", "Housing & Utilities"],
  ["telus", "Housing & Utilities"],
  ["fido", "Housing & Utilities"],
  ["koodo", "Housing & Utilities"],
  ["virgin plus", "Housing & Utilities"],
  ["freedom mobile", "Housing & Utilities"],
  ["chatr", "Housing & Utilities"],
  ["toronto hydro", "Housing & Utilities"],
  ["hydro one", "Housing & Utilities"],
  ["alectra", "Housing & Utilities"],
  ["enbridge", "Housing & Utilities"],
  ["epcor", "Housing & Utilities"],
  ["hydro", "Housing & Utilities"],
  ["utility", "Housing & Utilities"],

  // --- Education ---
  ["university", "Education"],
  ["college", "Education"],
  ["tuition", "Education"],
  ["udemy", "Education"],
  ["coursera", "Education"],
  ["skillshare", "Education"],
  ["duolingo", "Education"],

  // --- Services / shipping ---
  ["canada post", "Services"],
  ["purolator", "Services"],
  ["fedex", "Services"],
  ["ups store", "Services"],
  ["dry clean", "Services"],
  ["laundr", "Services"],

  // --- Government ---
  ["canada revenue", "Government"],
  ["service ontario", "Government"],
  ["service canada", "Government"],
  ["property tax", "Government"],
  ["passport canada", "Government"],

  // --- Fees / Debt ---
  ["overdraft", "Fees"],
  ["nsf fee", "Fees"],
  ["interest charge", "Fees"],
  ["service charge", "Fees"],
  ["monthly fee", "Fees"],
  ["atm fee", "Fees"],
  ["mortgage", "Debt"],
  ["line of credit", "Debt"],
  ["student loan", "Debt"],
  ["loan payment", "Debt"],

  // --- Shopping (general retail) — kept late so specific brands win first ---
  ["best buy", "Shopping"],
  ["the source", "Shopping"],
  ["staples", "Shopping"],
  ["indigo", "Shopping"],
  ["chapters", "Shopping"],
  ["ikea", "Shopping"],
  ["hudson's bay", "Shopping"],
  ["hudson bay", "Shopping"],
  ["the bay", "Shopping"],
  ["winners", "Shopping"],
  ["marshalls", "Shopping"],
  ["homesense", "Shopping"],
  ["dollarama", "Shopping"],
  ["dollar tree", "Shopping"],
  ["giant tiger", "Shopping"],
  ["sport chek", "Shopping"],
  ["sportchek", "Shopping"],
  ["mark's", "Shopping"],
  ["old navy", "Shopping"],
  ["h&m", "Shopping"],
  ["zara", "Shopping"],
  ["uniqlo", "Shopping"],
  ["lululemon", "Shopping"],
  ["aritzia", "Shopping"],
  ["simons", "Shopping"],
  ["foot locker", "Shopping"],
  ["roots", "Shopping"],
  ["london drugs", "Shopping"],
  ["canadian tire", "Shopping"],
  ["apple store", "Shopping"],
  ["walmart", "Shopping"],
  ["amazon", "Shopping"],
];

// Longest patterns first so specific names win over generic substrings.
const SORTED = [...MERCHANT_PATTERNS].sort((a, b) => b[0].length - a[0].length);

/** Detect a category from merchant/name text. Returns null when unknown. */
export function detectMerchantCategory(text: string): string | null {
  const hay = text.toLowerCase();
  for (const [pattern, category] of SORTED) {
    if (hay.includes(pattern)) return category;
  }
  return null;
}
